import { formatPKR } from "./calculations";
import { MONTH_NAMES, SUGGESTED_SPLITS } from "./constants";

/**
 * Generate a formatted WhatsApp-ready message after salary allocation.
 * Can be copied and pasted into WhatsApp.
 */
export function generateAllocationMessage(salary, fixedItems, fixedTotal, alloc, month, year) {
  const lines = [];

  lines.push(`🛡️ *CashGuard — ${MONTH_NAMES[month]} ${year} Budget*`);
  lines.push(`━━━━━━━━━━━━━━━━━━━━`);
  lines.push(``);
  lines.push(`💰 *Total Salary:* ${formatPKR(salary)}`);
  lines.push(``);
  lines.push(`📋 *Fixed Expenses:*`);
  for (const [, item] of Object.entries(fixedItems)) {
    lines.push(`   • ${item.label}: ${formatPKR(item.amount)}`);
  }
  lines.push(`   ─────────────`);
  lines.push(`   *Total Fixed:* ${formatPKR(fixedTotal)}`);
  lines.push(``);
  lines.push(`💵 *Available After Bills:* ${formatPKR(alloc.available)}`);
  lines.push(``);
  lines.push(`📊 *Distribution:*`);
  lines.push(`   💳 Spending (${SUGGESTED_SPLITS.spending}%): ${formatPKR(alloc.spending)}`);
  lines.push(`   🚗 Car Fund (${SUGGESTED_SPLITS.carFund}%): ${formatPKR(alloc.carFund)}`);
  lines.push(`   🛡️ Emergency (${SUGGESTED_SPLITS.emergencyFund}%): ${formatPKR(alloc.emergencyFund)}`);
  lines.push(``);
  lines.push(`━━━━━━━━━━━━━━━━━━━━`);
  lines.push(`_Generated by CashGuard_`);

  return lines.join("\n");
}

/** Generate daily summary message. */
export function generateDailySummary(remaining, dailyBudget, todaySpent, daysLeft, month) {
  const lines = [];
  const pct = remaining > 0 ? "✅" : "🚨";

  lines.push(`${pct} *CashGuard Daily — ${MONTH_NAMES[month]}*`);
  lines.push(`━━━━━━━━━━━━━━━━━━━━`);
  lines.push(``);
  lines.push(`💰 Remaining: ${formatPKR(remaining)}`);
  lines.push(`📈 Today's Limit: ${formatPKR(dailyBudget)}`);
  lines.push(`💸 Today's Spent: ${formatPKR(todaySpent)}`);
  lines.push(`📅 Days Left: ${daysLeft}`);
  lines.push(``);
  lines.push(`_Stay disciplined! 💪_`);

  return lines.join("\n");
}
